### ISSUE TITLE
Mesa redonda / apresentação para calouros de TADS e Técnico

### ISSUE THREAD

**Issue by luisdeol** [cades-ifrn/sobre#1]
**Boa tarde, pessoal!**

Gostaria de saber a opinião de vocês, se possível:

1. Quanto tempo seria suficiente para a mesa redonda?
2. Quantos profissionais que participariam falando (internos e externos)?
3. Qual seria o melhor dia para realiza-la?

_Atenciosamente,
Luis Felipe_

**Comment by davidallysson** [comment]
1. Acho que uma hora.
2. Por mim, dois internos e dois/três externos.
3. As aulas voltam após o carnaval, creio eu que dia 15 (quinta-feira). Sugiro que seja feita na segunda-feira, dia 22. Esses dias entre o dia 15 e o dia 22 podem ajudar para que o evento seja mais divulgado entre os alunos que estão chegando.

**Comment by albert06** [comment]
Se essa mesa for feita no seminário do primeiro dia terá que ser no dia 15.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by felipemfp** [comment]
Para fazer no seminário, acredito que teria que entrar em contato com os coordenadores do curso para planejar junto a eles a programação.

Sobre o tempo, 1h a 1h30 tá ótimo.

Uns 5 profissionais tá bom (como @davidallysson falou).

**Comment by AstroCarol** [comment]
1. 1h a 1h30m seria o tempo ideial, na minha opinião.
2.  5 profissionais tá ótimo (assim com @davidallysson comentou)
3. Séria bom entrar em contato com Plácido pra ver se tem como realizar a mesa dia 15/02 em conjunto com o seminário de integração.

**Comment by kessiacastro** [comment]
- Os seminários do superior e integrado vão acontecer nos dias 7 e 8 de fevereiro de acordo com o calendário acadêmico de 2018.

- Acho que 1h30 no máximo seria ideal.

- É preciso ter um mediador, alguém que vai nortear as conversas, fazer perguntas para que os três falem a respeito e debatam o assunto.

**Comment by luisdeol** [comment]
Galera, agora vamos para a "fase final" da organização do evento. Gostaria que vocês colocassem, de maneira organizada, **recomendações de perguntas a serem feitas aos profissionais de TI que estarão na mesa redonda.** 

Conto com a participação de vocês!

![image](https://user-images.githubusercontent.com/6783298/36333983-d966abf0-1358-11e8-8857-adc0fe1858e8.png)

**Comment by felipemfp** [comment]
Não sei formular perguntas, mas seria interessante puxar o assunto que tá ficando cada vez mais recorrente: "com as automações, o papel do desenvolvedor vai acabar?"; algo desse tipo.

Vamos ter sessão aberta para perguntas do público? O formato que foi Fr-Br School foi massa. A mesa redonda ia acontecendo e tinha papelzinho para a plateia escrever algumas perguntas, aí no momento certo, o apresentador pega um dos papelzinhos.

**Comment by kessiacastro** [comment]
# Perguntas (sugestões)

- Qual a maior dificuldade como desenvolvedor?
- O que você considera indispensável saber para ingressar no mercado de trabalho?
- Você Já desenvolveu algum sistema em que sentiu que estava contribuindo pra sociedade e não somente pra empresa?
- Qual a importância de participar da comunidade de TI na sua carreira/crescimento profissional?
- O mercado muda muito rápido, novas tecnologias sempre estão surgindo, alguma dica para se manter atualizado nesse contexto?
- Como você acha que o curso poderia contribuir com a sociedade e preparar os estudantes para o mercado ao mesmo tempo?

**Comment by luisdeol** [comment]
@felipemfp Sobre o modelo de mesa redonda, não fui ao Fr-Br School, mas soa bem! :)

Sobre a questão de "automação de desenvolvedor", temos que analisar se será um tema interessante a calouros de ambos os cursos. Talvez abordar os benefícios de inovações nas áreas de Negócios, Saúde, Segurança e Ensino seja uma forma mais branda e que curtam mais. O que acham?

Na minha opinião, após falar de importância da TI nesses campos, o resto da mesa poderia ser focado no mercado mesmo. :) Mas sinceramente acho imprescindível falarmos da importância da TI antes de pularmos ao mercado, principalmente pelos calouros (que sinceramente espero que venham em peso).

**Comment by kessiacastro** [comment]
Acho que automação e papel do desenvolvedor é muita coisa. Poderia haver outra mesa redonda só pra esse tema de tão abrangente que é a meu ver.

**Comment by luisdeol** [comment]
Obrigado a quem participou.

Como dito, fiquei de formular perguntas para a mesa para este fim de semana, as quais repassarei aos participantes. Por ser apenas 1h, e que discussões possam ser estender (principalmente sobre o tema da mesa redonda), foram formuladas 3 perguntas, e o resto do tempo será utilizado para perguntas do público.

**1. Em sua opinião, qual o papel da Tecnologia da Informação na Sociedade (abrangência, áreas, etc)?**

**2. Como você acha que o curso poderia contribuir para a formação de estudantes e a sociedade?**

**3.  Como você vê a participação de mulheres no mercado, e iniciativas como Code Girl, e de empresas como Google, Microsoft, que vem criando projetos e aumentando o percentual de mulheres na empresa?**

**4. Espaço para perguntas e respostas.**

Penso em aplicar o modelo que o Felipe propôs: 

"Vamos ter sessão aberta para perguntas do público? O formato que foi Fr-Br School foi massa. A mesa redonda ia acontecendo e tinha papelzinho para a plateia escrever algumas perguntas, aí no momento certo, o apresentador pega um dos papelzinhos."

É essa semana próxima! Vamos seguir divulgando aos amigos, por favor!

**Comment by kessiacastro** [comment]
Na mesa redonda que participei havia uma pessoa que fazia as perguntas e conduzia a mesa e as pessoas faziam perguntas no final.

**Comment by luisdeol** [comment]
@kessiacastro Então, o "momento certo" seria após a discussão das 3 pergunta. Eu acredito que a pessoa para conduzir a mesa e fazer as perguntas seria eu, por conhecer os dois participantes externos e ter conduzido a organização até agora.

**Comment by kessiacastro** [comment]
Vão ser só 3 perguntas? Acho que vai acabar muito rápido... É pra ser 1 hora?

**Comment by luisdeol** [comment]
Por experiência em mesas redondas e eventos de 1 hora, conversas se estendem muito rápido. Verei perguntas de reserva e publico por aqui, caso termine rápido. Mas duvido muito. Poderiamos adicionar algo sobre a experiência de cada um com a TI, aí certamente não terminaria rápido.

**Comment by felipemfp** [comment]
:clap: :clap: :clap: :clap: 

Parabéns a todos! Não estive presente, mas fiquei sabendo que foi um sucesso! :tada:
