### ISSUE TITLE
Organização dos times

### ISSUE THREAD

**Issue by felipemfp** [cades-ifrn/sobre#2]
> Cada equipe vai ficar responsável pelas seguintes atividades:
> 
> - Criar a enquete para definir o tema.
> - Entrar em contato com profissionais/alunos/pessoas que irão ministrar/participar do minicurso/palestra/mesa redonda
> - Criar inscrição
> - Divulgação
> - Organização geral do evento (reserva de sala/laboratório/etc)
> 
> As equipes estão listadas abaixo de acordo com as nossas atividades propostas. Então quem tiver interesse coloca o nome aí e o chefe definido da equipe em reunião hoje deverá se reunir com a equipe e dar andamento nessas atividades seguindo o cronograma proposto nas nossas metas.
> 
> Seguem as equipes:
> 
> Equipe Mesa Redonda:
> - Luis (Chefe)
> - Késsia
> 
> Equipe Hackathon:
> - Luis (Chefe)
> - Astro
> 
> Palestra:
> - Késsia
> - Astro (Chefe)
> 
> Minicurso:
> - Késsia
> - Albert
> - David
> - Mauro (Chefe)

_por @kessiacastro às 21:09, 15/1/2018 no [WhatsApp](https://chat.whatsapp.com/H6UWSSayqvO7kTeWKJ9jdb)_

Como vamos organizar? Um repositório para cada tópico? 

/cc @luisdeol @kessiacastro @AstroCarol @albert06 @davidallysson

**Comment by luisdeol** [comment]
Boa, @felipemfp !

> Como vamos organizar? Um repositório para cada tópico?

Acredito que um repositório para cada tópico seja bem válido!

Hoje mesmo crio o repositório para o Hackathon e para a mesa redonda!

@kessiacastro @AstroCarol

**Comment by felipemfp** [comment]
Eu acho válido principalmente por:

1. independência ao time para se organizar
2. visibilidade (podemos fixar na organização)
3. facilidade para encontrar conteúdos específicos (invés de ficar se misturando as issues aqui no sobre)

**Comment by luisdeol** [comment]
Ótimo, concordo!

**Comment by felipemfp** [comment]
Criei os times em https://github.com/orgs/cades-ifrn/teams.

Agora a gente pode mencionar o time inteiro numa issue:

- @cades-ifrn/hackathon 
- @cades-ifrn/mesa-redonda 
- @cades-ifrn/minicurso 
- @cades-ifrn/palestra 

Ficou faltando o Mauro ser adicionado no time de minicurso.

**Comment by felipemfp** [comment]
Fechando para reorganização do repositório.
