### ISSUE TITLE
ROADMAP para 2018

### ISSUE THREAD

**Issue by felipemfp** [cades-ifrn/sobre#3]
> Pessoal, na reunião de hoje definimos algumas ideias de palestras, minicursos, hackathons e mesa redondas que desejamos fazer nos próximos meses. Essas ideias não significam que vamos fazer TUDO, vamos criar enquetes com os temas listados abaixo para ver o que o pessoal quer e aí vamos fazendo de acordo com o interesse dos alunos (TADS e Técnico).
> 
> Nossa primeira atividade de 2018 será uma mesa redonda sobre as carreiras em TI para o pessoal que está iniciando. As outras atividades serão definidas por votação no Facebook no grupo de TADS.
> 
> Seguem as ideias que listamos:
> 
> Mini Curso - Ideias
> - Chat bot
> - Api com Flask
> - Api com Node
> - Programa com Electron
> - Robótica
> - Grafos e ArangoDB
> - API Gateway - Kong
> - Introdução ao Linux
> - Introdução ao Git
> 
> Mesa Redonda:
> - Áreas da TI
> - React x Angular x Vue
> - Python x Ruby
> - Frameworks HTML/CSS ou não?
> 
> Palestra:
> - Palestra Web Scraping - Mauro
> - HTML, CSS e Javascript
> - Pré-processadores
> - Orquestração
> - Banco de Dados - SQL, Models, ORM
> - Docker
> - Proxy Reverso
> 
> Criar conteúdo para um mini curso de um dia do zero a um projeto finalizado estilo Django Girls: https://tutorial.djangogirls.org/pt/
> 
> Criar Roadmaps de tutoriais/palestras: Front End, Back End, DevOps

_por @kessiacastro às 21:06, 15/1/2018 no [WhatsApp](https://chat.whatsapp.com/H6UWSSayqvO7kTeWKJ9jdb)_

**Comment by felipemfp** [comment]
Um minicurso bem interessante seria uma **Introdução a [GraphQL](http://graphql.org/)**.

Um minicurso de **Docker** também seria bem aceito, acredito. Assim como uma palestra sobre novos padrões de arquitetura como **Microserviços** e **Serverless**.

**Comment by felipemfp** [comment]
Outra tecnologia do ecossistema React que tá crescendo muito é o **[Gatsby](https://github.com/gatsbyjs/gatsby)**. É ótimo para iniciantes (_zero config_) e para criação de sites estáticos (blogs, páginas institutionais etc).

**Comment by felipemfp** [comment]
@yuriscosta, tem interesse em compartilhar seu conhecimento com Chatbots?

**Comment by luisdeol** [comment]
> Assim como uma palestra sobre novos padrões de arquitetura como Microserviços e Serverless.  


Já palestrei sobre Serverless (na [DevWeek](http://devweek.azurewebsites.net/), evento online) e tenho grande interesse por arquiteturas (estou começando a preparar e estudar material para publicar sobre Microserviços com containers Docker).

Se precisarem de auxílio nisso, só avisar que contribuo como puder (já que não estou na equipe de mini-cursos, mas se precisar poderia apresentar).

**Comment by yuriscosta** [comment]
@felipemfp infelizmente nesse primeiro semestre do ano não terei muito tempo disponível para colaborar nos minicursos. Mas eu posso ir me organizando para que no começo do segundo semestre eu possa ministrar minicursos sobre bioinformática e/ou chatbots com processamento de linguagem natural.

**Comment by felipemfp** [comment]
> Mas eu posso ir me organizando para que no começo do segundo semestre eu possa ministrar minicursos sobre bioinformática e/ou chatbots com processamento de linguagem natural.

Fica a dica, @cades-ifrn/minicurso.

> uma ideia que eu tive pra palestras é tratar da inteligência artificial por trás das fake news, já que é o tema que estou trabalhando no meu trabalho de conclusão de curso.

@cades-ifrn/palestra 

Eu também tenho experiência em Docker e microsserviços (trabalho com isso no @LAIS-HUOL), se precisar tamo aí.

**Comment by chicobentojr** [comment]
> @felipemfp uma ideia que eu tive pra palestras é tratar da inteligência artificial por trás das fake news, já que é o tema que estou trabalhando no meu trabalho de conclusão de curso.

@yuriscosta, tô começando a estudar sobre IA também, daqui pra lá acho que posso tentar ajudar em algo.

**Comment by felipemfp** [comment]
Fechando para reorganização do repositório.
