### ISSUE TITLE
Propostas para a logo

### ISSUE THREAD

**Issue by felipemfp** [cades-ifrn/sobre#4]
Nesta issue, trataremos das propostas para a logo.

**Comment by felipemfp** [comment]
![Logo feita pelo Lucas Miquéais do GDG Natal](https://user-images.githubusercontent.com/8146112/35116402-1635c53a-fc6a-11e7-90ec-79af7a81e291.png)

[Logo](https://imgur.com/a/q7AWo) feita pelo @lucasmiqueias participante do @gdg-natal.

**Comment by HeloraDana** [comment]
![artboard 2-100](https://user-images.githubusercontent.com/18369364/35151540-dbba48da-fd05-11e7-8841-59d037627de3.jpg)

**Comment by felipemfp** [comment]
Show demais, @HeloraDana

**Comment by kessiacastro** [comment]
Só lembrem de fazer em formato vetorizado que aí dá pra esticar ela em qualquer tamanho. /o/

**Comment by gionogueira** [comment]
# Logo Cades
### Essa logo foi criada com o conceito de uma célula com várias bolas interligadas que representam cada elemento que pertence ao Cades: cooperação, eventos acadêmicos, união, tecnologia, desenvolvimento e open source e web. Sendo então todos esses elementos ligados ao nome CADES.

![logocades](https://user-images.githubusercontent.com/25420543/36102065-df64232e-0fe9-11e8-9d5e-60e673ed6d4c.png)

**Comment by felipemfp** [comment]
Vou abrir uma issue para votação :smile:

**Comment by gionogueira** [comment]
As cores são iguais do WTADS pois pensei em criar uma única identidade visual para os eventos do nosso curso.

**Comment by felipemfp** [comment]
Votação aberta: #6
